// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFe5hv0I9qXiW7UGL4Hf7zyNlxSY1QIgc',
    appId: '1:334330178934:web:8dbb3d862099b468c09e57',
    messagingSenderId: '334330178934',
    projectId: 'unmask-31026',
    authDomain: 'unmask-31026.firebaseapp.com',
    storageBucket: 'unmask-31026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSIn62TpaC-Og-QUsjTCQ5xrjXMBU4KfM',
    appId: '1:334330178934:android:58dfa396ff0a2b5cc09e57',
    messagingSenderId: '334330178934',
    projectId: 'unmask-31026',
    storageBucket: 'unmask-31026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTVpIs5D6PRJxOndCs7yABI74b4EopZs',
    appId: '1:334330178934:ios:25c1d37b794265e3c09e57',
    messagingSenderId: '334330178934',
    projectId: 'unmask-31026',
    storageBucket: 'unmask-31026.appspot.com',
    iosClientId: '334330178934-c3cm5kr08q1g6sgcgmv02dg52hjkaubm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepfake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTVpIs5D6PRJxOndCs7yABI74b4EopZs',
    appId: '1:334330178934:ios:25c1d37b794265e3c09e57',
    messagingSenderId: '334330178934',
    projectId: 'unmask-31026',
    storageBucket: 'unmask-31026.appspot.com',
    iosClientId: '334330178934-c3cm5kr08q1g6sgcgmv02dg52hjkaubm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepfake',
  );
}
